apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: deep-research-backend-config
  namespace: deep-research
spec:
  timeoutSec: 300
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
  logging:
    enable: true
    sampleRate: 1.0
  customRequestHeaders:
    headers:
    - "Cache-Control:no-cache"
    - "Connection:keep-alive"