apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-research-backend
  namespace: deep-research
  labels:
    app: deep-research-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deep-research-backend
  template:
    metadata:
      labels:
        app: deep-research-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/${PROJECT_ID}/deep-research-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: deep-research-secrets
              key: gemini-api-key
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: deep-research-secrets
              key: langsmith-api-key
              optional: true
        - name: REDIS_URI
          value: "redis://deep-research-redis:6379"
        - name: POSTGRES_URI
          value: "postgres://postgres:postgres@deep-research-postgres:5432/postgres?sslmode=disable"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: deep-research-backend
  namespace: deep-research
  annotations:
    cloud.google.com/backend-config: '{"default": "deep-research-backend-config"}'
spec:
  selector:
    app: deep-research-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP