apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deep-research-ingress
  namespace: deep-research
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "deep-research-ip"
    networking.gke.io/managed-certificates: "deep-research-ssl-cert"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: ${DOMAIN_NAME}
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: deep-research-frontend
            port:
              number: 80
      - path: /app/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: deep-research-frontend
            port:
              number: 80
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: deep-research-backend
            port:
              number: 80
      - path: /threads
        pathType: Prefix
        backend:
          service:
            name: deep-research-backend
            port:
              number: 80